### ISSUE TITLE
itm to you human resource!

### ISSUE THREAD

**Issue by adamkowalewski** [NoAgenda/noagendastream#1]
This request, to add me to this organization, is important, the substance is right, the time is right and the way in which it has been developed is right.

cya
Adam

**Comment by voidzero** [comment]
Woops!

I just heard John mention you. I forgot to approve, sorry, had a lot of stuff going on :-)

**Comment by adamkowalewski** [comment]
yeaiii

**Comment by NoAgendaIT** [comment]
Invitation sent :+1:
